### ISSUE TITLE
file path for complex schemas

### ISSUE THREAD

**Issue by cemtopkaya** [chute/json-schema-defaults#5]
I want to create schemas in separate files (most of them complex and reusable). Is there any way to create objects with giving main schema path?
<pre>
- job.json
- address.json
- person.json
  - $ref : address.json#address
  - $ref : job.json#job
var p = require('json-schema-defaults')('./person.json')</pre>

**Comment by petrbela** [comment]
@cemtopkaya This project doesn't deal with accessing `File`s because it's out of its scope, and it would also prevent it from being used in a browser. What you can do is load the JSON file yourself, and pass it to the function:

```js
var defaults = require('json-schema-defaults')
var person = require('./person.json')  // or JSON.parse(require('fs').readFileSync('./person.json'))
var p = defaults(person)
```

Cross references are currently not supported but you might be able to do something like

```js
var person = require('./person.json')
person.address = require('./address.json')
person.job = require('./job.json')

var p = defaults(person)
```
